CREATE DEFINER=`root`@`localhost` EVENT `DeleteDead` ON SCHEDULE EVERY 1 HOUR STARTS '2013-05-28 09:12:27' ON COMPLETION PRESERVE ENABLE DO DELETE FROM `Character_DATA` WHERE Alive = 0//

CREATE DEFINER=`root`@`localhost` EVENT `DeleteDestroyedVehicles` ON SCHEDULE EVERY 1 HOUR STARTS '2013-07-23 02:51:53' ON COMPLETION PRESERVE ENABLE DO DELETE FROM `Object_DATA` WHERE Damage = 1//

CREATE DEFINER=`root`@`localhost` EVENT `updateStockDaily` ON SCHEDULE EVERY 1 HOUR STARTS '2013-07-23 02:51:53' ON COMPLETION PRESERVE ENABLE DO UPDATE `Traders_DATA` SET qty=50 WHERE qty<20//